/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-hoverable-behavior.html
 */

/// <reference path="../polymer/types/lib/utils/mixin.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />

declare namespace Anypoint {


  /**
   * **Note:** This is closed software and you can't use it in your projects unless
   * you are a Mulesoft employee working on internall project.
   *
   * Use `Anypoint.AnypointHoverableBehavior` to implement an element that can be hovered.
   * The control will get a `hovered` attribute when it's hovered by the poiting devide.
   *
   * Be aware that mobile devices will not support hovering as desktop devices and behavior
   * may vary depending on platform. You should use this as little as possible.
   */
  function HoverableBehavior<T extends new (...args: any[]) => {}>(base: T): T & HoverableBehaviorConstructor;

  interface HoverableBehaviorConstructor {
    new(...args: any[]): HoverableBehavior;
  }

  interface HoverableBehavior {

    /**
     * Set to `true` when the control is currently being hovered.
     */
    hovered: boolean|null|undefined;

    /**
     * Registers hover listeners
     */
    connectedCallback(): void;

    /**
     * Removes hover listeners
     */
    disconnectedCallback(): void;

    /**
     * Set's the `hovered` attribute to true when handled.
     */
    _hoverCallback(): void;

    /**
     * Updates `hovered` if the control is not hovered anymore.
     */
    _leaveCallback(): void;
  }
}
