/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-behaviors.html
 */

/// <reference path="anypoint-hoverable-behavior.d.ts" />

